version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql  # Asegúrate que este nombre coincida
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: midb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contrasena
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URI: mysql+pymysql://root:rootpassword@localhost:3306/midb
      JWT_SECRET_KEY: myjwtsecret

volumes:
  db_data:
